export const PAGE_TYPES = [
  "Service Page",
  "Home Page",
  "Service-Area Page",
  "City Page",
  "Product Page",
  "Landing Page",
  "Entity-Destination Page",
  "Venue Page",
  "Event-Calendar Page",
  "Events Page",
  "Menu Page",
  "Inventory-List Page",
  "About-Us Page",
  "Team Page",
  "Contact-Us Page",
  "Blog Page",
  "Blog Post",
  "FAQ Page",
  "Q&A Page",
  "Category Page",
  "Tag Page",
  "Index Page",
] as const;

export type PageType = (typeof PAGE_TYPES)[number];
