import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { createServerClient } from "@/lib/supabase";
import { getCurrentUser } from "@/lib/auth";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { reportId, email } = await request.json();

    if (!reportId || !email) {
      return NextResponse.json(
        { error: "Report ID and email are required" },
        { status: 400 }
      );
    }

    // 从数据库获取报告
    const supabase = createServerClient();
    const { data: report, error } = await supabase
      .from("reports")
      .select("*")
      .eq("id", reportId)
      .eq("user_id", user.userId)
      .single();

    if (error || !report) {
      return NextResponse.json({ error: "Report not found" }, { status: 404 });
    }

    if (report.status !== "paid_full") {
      return NextResponse.json(
        { error: "Report must be unlocked before sending" },
        { status: 403 }
      );
    }

    // 发送邮件
    const { data, error: sendError } = await resend.emails.send({
      from: "SearchTrust <noreply@trysearchtrust.com>",
      to: email,
      subject: `Trust Audit Report — ${report.page_url}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #F8F9FA; margin: 0; padding: 40px 20px; }
            .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 24px; overflow: hidden; border: 1px solid #f0f0f0; }
            .header { background: #1D2531; padding: 32px; text-align: center; }
            .header h1 { color: white; margin: 0; font-size: 24px; }
            .header .subtitle { color: #A5D020; font-size: 14px; margin-top: 8px; }
            .content { padding: 32px; }
            .meta { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 24px; }
            .tag { background: #F8F9FA; border: 1px solid #f0f0f0; border-radius: 20px; padding: 6px 16px; font-size: 12px; color: #6B7280; font-weight: 700; }
            .scores { display: flex; gap: 16px; margin-bottom: 24px; }
            .score-card { flex: 1; background: #F8F9FA; border-radius: 16px; padding: 20px; text-align: center; }
            .score-label { font-size: 12px; color: #9CA3AF; font-weight: 700; margin-bottom: 8px; }
            .score-value { font-size: 20px; font-weight: 900; }
            .section { margin-top: 24px; }
            .section-title { font-size: 18px; font-weight: 700; margin-bottom: 12px; }
            .footer { text-align: center; padding: 24px; color: #9CA3AF; font-size: 12px; }
            .btn { display: inline-block; background: #1D2531; color: white; padding: 12px 32px; border-radius: 30px; text-decoration: none; font-weight: 700; font-size: 14px; margin-top: 16px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Trust Audit Report</h1>
              <div class="subtitle">Generated by SearchTrust</div>
            </div>
            <div class="content">
              <div class="meta">
                <span class="tag">URL: ${report.page_url}</span>
                <span class="tag">Page Type: ${report.page_type || "N/A"}</span>
                <span class="tag">Report ID: ${report.report_id}</span>
              </div>
              <div class="scores">
                <div class="score-card">
                  <div class="score-label">Trust Status</div>
                  <div class="score-value" style="color: #3B82F6">${report.trust_status || "—"}</div>
                </div>
                <div class="score-card">
                  <div class="score-label">Ranking Potential</div>
                  <div class="score-value" style="color: #A5D020">${report.ranking_potential || "—"}</div>
                </div>
                <div class="score-card">
                  <div class="score-label">Risk Level</div>
                  <div class="score-value" style="color: #EF4444">${report.risk_level || "—"}</div>
                </div>
              </div>
              <div style="text-align: center;">
                <a href="https://yourdomain.com/reports" class="btn">View Full Report</a>
              </div>
            </div>
            <div class="footer">
              This report was generated by SearchTrust.<br>
              You received this email because someone requested to send a report to this address.
            </div>
          </div>
        </body>
        </html>
      `,
    });

    if (sendError) {
      console.error("Resend error:", sendError);
      return NextResponse.json(
        { error: "Failed to send email" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error("Send report error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
